version: "3"
services:

  wordpress:
    image: wordpress:latest
    container_name: "wordpress"
    volumes:
      - ./volume/wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/wptm
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      APACHE_RUN_USER: "#33"
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user_pass_Ck6uTvrQ

  db:
    image: mysql:5.7
    container_name: "mysql57"
    restart: always
    volumes:
      - ./volume/database/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass_fB3uWvTS
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass_Ck6uTvrQ

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
