version: "3.7"
services:

  wordpress:
    container_name: "wordpress"
    env_file: .env
    build:
      context: ./build/wordpress
      args:
        WP_INSTALL_DIR: ${WP_INSTALL_DIR}
        WWWDATA_USERID: ${WWWDATA_USERID}
    links:
      - database:mysql
    volumes:
      - ./volume/static:${WP_INSTALL_DIR}/static
      - ./volume/content:${WP_INSTALL_DIR}/wp-content
      - ./theme:${WP_INSTALL_DIR}/wp-content/themes/wptm
      - ./config:/opt/config
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "${HTTP_CLIENT_PORT}:80"
      - "${HTTPS_CLIENT_PORT}:443"
    environment:
      SERVER_LOCALE: ${SERVER_LOCALE}
      SERVER_TIMEZONE: ${SERVER_TIMEZONE}
      WP_INSTALL_DIR: ${WP_INSTALL_DIR}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_PLUGIN_LIST: ${WP_PLUGIN_LIST}
      WORDPRESS_DB_HOST: mysql:${DB_CLIENT_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

  database:
    image: mysql:5.7
    container_name: "mysql"
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./volume/database/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_SECRET}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    restart: always
    depends_on:
      - database
    ports:
      - 8888:${PHPMYADMIN_CLIENT_PORT}
